/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas.Admin;

import Datos.Central;
import Ventanas.Principal;
import javax.swing.JOptionPane;

/**
 *
 * @author Guillermo
 */
public class ModificaFecha extends javax.swing.JFrame {
   private static Central datos;
   /**
    * Creates new form ModificaFecha
    * @param data
    */
   public ModificaFecha(Central data) {
      initComponents();
      this.datos = data;
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jButtonActualizar = new javax.swing.JButton();
      jButtonLimpia = new javax.swing.JButton();
      jFormattedTextFieldFecha = new javax.swing.JFormattedTextField();
      jButtonAtras = new javax.swing.JButton();
      jScrollPane1 = new javax.swing.JScrollPane();
      jTextAreaNota = new javax.swing.JTextArea();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("Modificar Fecha");
      setLocation(new java.awt.Point(300, 200));

      jPanel1.setBackground(new java.awt.Color(255, 255, 255));
      jPanel1.setMinimumSize(null);

      jButtonActualizar.setBackground(new java.awt.Color(102, 255, 102));
      jButtonActualizar.setText("Actualizar");
      jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonActualizarActionPerformed(evt);
         }
      });

      jButtonLimpia.setBackground(new java.awt.Color(255, 51, 51));
      jButtonLimpia.setText("Limpiar");
      jButtonLimpia.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonLimpiaActionPerformed(evt);
         }
      });

      try {
         jFormattedTextFieldFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/#### ##:##:##")));
      } catch (java.text.ParseException ex) {
         ex.printStackTrace();
      }
      jFormattedTextFieldFecha.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jFormattedTextFieldFechaActionPerformed(evt);
         }
      });

      jButtonAtras.setText("Atras");
      jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonAtrasActionPerformed(evt);
         }
      });

      jTextAreaNota.setEditable(false);
      jTextAreaNota.setColumns(20);
      jTextAreaNota.setLineWrap(true);
      jTextAreaNota.setRows(5);
      jTextAreaNota.setText("Nota: La fecha es tomada de su PC, pero puede ser modificada  en esta opcion para facilitar el proceso de vencimiento de los \nobjetos empeñados.");
      jScrollPane1.setViewportView(jTextAreaNota);

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jButtonAtras)
                  .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
               .addComponent(jFormattedTextFieldFecha)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jButtonLimpia)
                  .addGap(18, 18, 18)
                  .addComponent(jButtonActualizar)))
            .addGap(22, 22, 22))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jFormattedTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jButtonActualizar)
               .addComponent(jButtonLimpia))
            .addGap(18, 18, 18)
            .addComponent(jButtonAtras)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void jFormattedTextFieldFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldFechaActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jFormattedTextFieldFechaActionPerformed

   private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
      if (jFormattedTextFieldFecha.getText().replaceAll("[ ,/]", "").length() != 8) {
         JOptionPane.showMessageDialog(null, "El campo de fecha está incompleto");
      }
      else{
         if (datos.verificaFecha(jFormattedTextFieldFecha.getText())) {
            datos.setFechaMod(jFormattedTextFieldFecha.getText());
            limpiaFormulario();
            JOptionPane.showMessageDialog(null, "Fecha actualizada!");
         }
      }
   }//GEN-LAST:event_jButtonActualizarActionPerformed

   private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
      Principal princi = new Principal(datos);
      princi.setVisible(true);
      dispose();
   }//GEN-LAST:event_jButtonAtrasActionPerformed

   private void jButtonLimpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiaActionPerformed
      limpiaFormulario();
   }//GEN-LAST:event_jButtonLimpiaActionPerformed

   public void limpiaFormulario(){
      jFormattedTextFieldFecha.setValue(null);
   }
   
   public void horaActual(){
      String horaInicio = datos.getFechaInicial();
      String horaActual = datos.generaFecha();
      
   }
   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(ModificaFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(ModificaFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(ModificaFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(ModificaFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new ModificaFecha(datos).setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButtonActualizar;
   private javax.swing.JButton jButtonAtras;
   private javax.swing.JButton jButtonLimpia;
   private javax.swing.JFormattedTextField jFormattedTextFieldFecha;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextArea jTextAreaNota;
   // End of variables declaration//GEN-END:variables
}
