/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas.Admin;

import Datos.Central;
import Ventanas.Principal;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guillermo
 */
public class ReportVentas extends javax.swing.JFrame {
   public static Central datos;
   /**
    * Creates new form ReportVentas
    * @param data
    */
   public ReportVentas(Central data) {
      initComponents();
      this.datos = data;
      llenaTabla();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jButtonAtras = new javax.swing.JButton();
      jLabelNota = new javax.swing.JLabel();
      jScrollPane1 = new javax.swing.JScrollPane();
      jTableVendidos = new javax.swing.JTable();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Reporte de Ventas");
      setLocation(new java.awt.Point(300, 200));
      setResizable(false);

      jPanel1.setBackground(new java.awt.Color(255, 255, 255));

      jButtonAtras.setText("Atras");
      jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonAtrasActionPerformed(evt);
         }
      });

      jLabelNota.setText("Nota: La fecha de retiro hace referencia a cuando se ha venvido el articulo.");

      jTableVendidos.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {
            "N°", "Nombre", "Precio", "Fecha Ingreso", "Fecha Retiro", "Cantidad"
         }
      ) {
         Class[] types = new Class [] {
            java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
         };
         boolean[] canEdit = new boolean [] {
            false, false, false, false, false, false
         };

         public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
         }

         public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
         }
      });
      jScrollPane1.setViewportView(jTableVendidos);
      if (jTableVendidos.getColumnModel().getColumnCount() > 0) {
         jTableVendidos.getColumnModel().getColumn(0).setResizable(false);
         jTableVendidos.getColumnModel().getColumn(0).setPreferredWidth(7);
         jTableVendidos.getColumnModel().getColumn(1).setResizable(false);
         jTableVendidos.getColumnModel().getColumn(1).setPreferredWidth(250);
         jTableVendidos.getColumnModel().getColumn(2).setResizable(false);
         jTableVendidos.getColumnModel().getColumn(2).setPreferredWidth(50);
         jTableVendidos.getColumnModel().getColumn(3).setResizable(false);
         jTableVendidos.getColumnModel().getColumn(3).setPreferredWidth(100);
         jTableVendidos.getColumnModel().getColumn(4).setResizable(false);
         jTableVendidos.getColumnModel().getColumn(4).setPreferredWidth(100);
         jTableVendidos.getColumnModel().getColumn(5).setResizable(false);
         jTableVendidos.getColumnModel().getColumn(5).setPreferredWidth(50);
      }

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jButtonAtras)
                  .addGap(18, 18, 18)
                  .addComponent(jLabelNota)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jButtonAtras)
               .addComponent(jLabelNota))
            .addContainerGap())
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
      Principal princi = new Principal(datos);
      princi.setVisible(true);
      dispose();
   }//GEN-LAST:event_jButtonAtrasActionPerformed
   public void llenaTabla(){
      DefaultTableModel modelo = (DefaultTableModel) jTableVendidos.getModel();
      modelo.setRowCount(0);
      for (int i = 0; i < datos.getVendidos().size(); i++) {        
         System.out.println(datos.getVendidos().get(i).toString());
         modelo.addRow(new Object[]{(i + 1), datos.getVendidos().get(i).getNombre(), datos.getVendidos().get(i).getValor()
                 , datos.getVendidos().get(i).getFechaIngreso(), datos.getVendidos().get(i).getFechaSalida(), 
                 datos.getVendidos().get(i).getCantidad()});
      }
   }
   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(ReportVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(ReportVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(ReportVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(ReportVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new ReportVentas(datos).setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButtonAtras;
   private javax.swing.JLabel jLabelNota;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTable jTableVendidos;
   // End of variables declaration//GEN-END:variables
}
