/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas.Empleado;

import Datos.Central;
import Datos.Persistencia;
import Ventanas.Principal;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Guillermo
 */
public class Compra extends javax.swing.JFrame {
   private static Central datos;
   private Persistencia archivo = new Persistencia();
   /**
    * Creates new form Compra
    * @param data
    */
   public Compra(Central data) {
      initComponents();
      this.datos = data;
      this.setLocationRelativeTo(null);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jTextFieldNombre = new javax.swing.JTextField();
      jLabelNombre = new javax.swing.JLabel();
      jLabelValor = new javax.swing.JLabel();
      jLabelFecha = new javax.swing.JLabel();
      jLabelCantidad = new javax.swing.JLabel();
      jButtonAtras = new javax.swing.JButton();
      jButtonCompra = new javax.swing.JButton();
      jButtonLimpiar = new javax.swing.JButton();
      jFormattedTextFieldFecha = new javax.swing.JFormattedTextField();
      jFormattedTextFieldValor = new javax.swing.JFormattedTextField();
      jFormattedTextFieldCantidad = new javax.swing.JFormattedTextField();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Compra de Articulo");
      setLocation(new java.awt.Point(0, 0));
      setResizable(false);

      jPanel1.setBackground(new java.awt.Color(255, 255, 255));
      jPanel1.setToolTipText("");

      jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldNombreActionPerformed(evt);
         }
      });
      jTextFieldNombre.addKeyListener(new KeyAdapter() {
         @Override
         public void keyTyped(KeyEvent e) {
            if (jTextFieldNombre.getText().length() == 40 ){
               JOptionPane.showMessageDialog(null, "El limite de caracteres para el nombre es 40");
               e.consume();
            }
         }
      });

      jLabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      jLabelNombre.setText("Nombre:");

      jLabelValor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      jLabelValor.setText("Valor:");

      jLabelFecha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      jLabelFecha.setText("Fecha(DD-MM-YYYY):");

      jLabelCantidad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      jLabelCantidad.setText("Cantidad:");

      jButtonAtras.setText("Atras");
      jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonAtrasActionPerformed(evt);
         }
      });

      jButtonCompra.setBackground(new java.awt.Color(102, 255, 102));
      jButtonCompra.setText("Comprar");
      jButtonCompra.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonCompraActionPerformed(evt);
         }
      });

      jButtonLimpiar.setBackground(new java.awt.Color(255, 51, 51));
      jButtonLimpiar.setText("Limpiar");
      jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonLimpiarActionPerformed(evt);
         }
      });

      try {
         jFormattedTextFieldFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
      } catch (java.text.ParseException ex) {
         ex.printStackTrace();
      }

      jFormattedTextFieldValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
      jFormattedTextFieldValor.addKeyListener(new KeyAdapter() {
         @Override
         public void keyTyped(KeyEvent e) {
            if (jFormattedTextFieldValor.getText().length() == 9 ){
               JOptionPane.showMessageDialog(null, "El limite para la cantidad es de 9 digitos");
               e.consume();
            }
         }
      });

      jFormattedTextFieldCantidad.addKeyListener(new KeyAdapter() {
         @Override
         public void keyTyped(KeyEvent e) {
            if (jFormattedTextFieldCantidad.getText().length() == 9 ){
               JOptionPane.showMessageDialog(null, "El limite para la cantidad es de 9 digitos");
               e.consume();
            }
         }
      });
      jFormattedTextFieldCantidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(jButtonAtras))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(41, 41, 41)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCompra))
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabelCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                              .addComponent(jFormattedTextFieldCantidad, javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(jFormattedTextFieldValor, javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(jFormattedTextFieldFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))))))
            .addContainerGap(52, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(36, 36, 36)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabelNombre, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jFormattedTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabelValor))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jFormattedTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabelFecha))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jFormattedTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabelCantidad))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jButtonCompra)
               .addComponent(jButtonLimpiar))
            .addGap(18, 18, 18)
            .addComponent(jButtonAtras)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
      Principal princi = new Principal(datos);
      princi.setVisible(true);
      dispose();
   }//GEN-LAST:event_jButtonAtrasActionPerformed

   private void jButtonCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCompraActionPerformed
      if (jTextFieldNombre.getText().isEmpty()) {
         JOptionPane.showMessageDialog(null, "El campo de nombre está vacio");
      }
      else if (Integer.parseInt(jFormattedTextFieldValor.getText()) == 0) {
         JOptionPane.showMessageDialog(null, "El campo de valor es invalido");
      }
      else if (jFormattedTextFieldFecha.getText().replaceAll("[ ,/]", "").length() != 8) {
         JOptionPane.showMessageDialog(null, "El campo de fecha está incompleto");
      }
      else if (jFormattedTextFieldCantidad.getText().isEmpty()) {
         JOptionPane.showMessageDialog(null, "El campo de cantidad está vacio");
      }
      else{
         if (datos.verificaCompra(jTextFieldNombre.getText(), Integer.parseInt(jFormattedTextFieldValor.getText()), 
                 jFormattedTextFieldFecha.getText(), Integer.parseInt(jFormattedTextFieldCantidad.getText()))) {
            limpiarFormulario();
            JOptionPane.showMessageDialog(null, "Articulo Comprado!");
            try {
               archivo.guardar(datos);
            } catch (IOException ex) {
               Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
      }
   }//GEN-LAST:event_jButtonCompraActionPerformed

   private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
      limpiarFormulario();
   }//GEN-LAST:event_jButtonLimpiarActionPerformed

   private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
      
   }//GEN-LAST:event_jTextFieldNombreActionPerformed
   private void limpiarFormulario(){
      jTextFieldNombre.setText("");
      jFormattedTextFieldValor.setText("");
      jFormattedTextFieldFecha.setValue(null);
      jFormattedTextFieldCantidad.setText("");
   }
   
   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new Compra(datos).setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButtonAtras;
   private javax.swing.JButton jButtonCompra;
   private javax.swing.JButton jButtonLimpiar;
   private javax.swing.JFormattedTextField jFormattedTextFieldCantidad;
   private javax.swing.JFormattedTextField jFormattedTextFieldFecha;
   private javax.swing.JFormattedTextField jFormattedTextFieldValor;
   private javax.swing.JLabel jLabelCantidad;
   private javax.swing.JLabel jLabelFecha;
   private javax.swing.JLabel jLabelNombre;
   private javax.swing.JLabel jLabelValor;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JTextField jTextFieldNombre;
   // End of variables declaration//GEN-END:variables
}
