/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas.Empleado;

import Datos.Central;
import Ventanas.Principal;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Guillermo
 */
public class Empenio extends javax.swing.JFrame {
   private static Central datos;
   /**
    * Creates new form Empenio
    * @param data
    */
   public Empenio(Central data) {
      initComponents();
      this.datos = data;
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jLabelNombre = new javax.swing.JLabel();
      jLabelMonto = new javax.swing.JLabel();
      jLabelFechaIngreso = new javax.swing.JLabel();
      jLabelFechaRetiro = new javax.swing.JLabel();
      jLabelCantidad = new javax.swing.JLabel();
      jTextFieldNombre = new javax.swing.JTextField();
      jButtonEmpenar = new javax.swing.JButton();
      jButtonAtras = new javax.swing.JButton();
      jButtonLimpia = new javax.swing.JButton();
      jFormattedTextFieldMonto = new javax.swing.JFormattedTextField();
      jFormattedTextFieldFechaIngreso = new javax.swing.JFormattedTextField();
      jFormattedTextFieldFechaRetiro = new javax.swing.JFormattedTextField();
      jFormattedTextFieldCantidad = new javax.swing.JFormattedTextField();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Empeñar Articulo");
      setLocation(new java.awt.Point(300, 200));
      setResizable(false);

      jPanel1.setBackground(new java.awt.Color(255, 255, 255));

      jLabelNombre.setText("Nombre:");

      jLabelMonto.setText("Monto: ");

      jLabelFechaIngreso.setText("Fecha Ingreso(DD-MM-YYYY):");

      jLabelFechaRetiro.setText("Fecha Retiro(DD-MM-YYYY):");

      jLabelCantidad.setText("Cantidad:");

      jTextFieldNombre.addKeyListener(new KeyAdapter() {
         @Override
         public void keyTyped(KeyEvent e) {
            if (jTextFieldNombre.getText().length() == 40 ){
               JOptionPane.showMessageDialog(null, "El limite para el nombre es de 40 caracteres");
               e.consume();
            }
         }
      });

      jButtonEmpenar.setBackground(new java.awt.Color(102, 255, 102));
      jButtonEmpenar.setText("Empeñar");
      jButtonEmpenar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonEmpenarActionPerformed(evt);
         }
      });

      jButtonAtras.setText("Atras");
      jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonAtrasActionPerformed(evt);
         }
      });

      jButtonLimpia.setBackground(new java.awt.Color(255, 51, 51));
      jButtonLimpia.setText("Limpiar");
      jButtonLimpia.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonLimpiaActionPerformed(evt);
         }
      });

      jFormattedTextFieldMonto.addKeyListener(new KeyAdapter() {
         @Override
         public void keyTyped(KeyEvent e) {
            if (jFormattedTextFieldMonto.getText().length() == 9 ){
               JOptionPane.showMessageDialog(null, "El limite para el monto es de 9 digitos");
               e.consume();
            }
         }
      });
      jFormattedTextFieldMonto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

      try {
         jFormattedTextFieldFechaIngreso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
      } catch (java.text.ParseException ex) {
         ex.printStackTrace();
      }

      try {
         jFormattedTextFieldFechaRetiro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
      } catch (java.text.ParseException ex) {
         ex.printStackTrace();
      }

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(jButtonAtras)
                  .addGap(0, 0, Short.MAX_VALUE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(32, 32, 32)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(jLabelMonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(jLabelFechaIngreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabelFechaRetiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(jLabelCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                  .addGap(18, 18, 18)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jFormattedTextFieldMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jFormattedTextFieldFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jFormattedTextFieldFechaRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jFormattedTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jButtonLimpia)
                  .addGap(18, 18, 18)
                  .addComponent(jButtonEmpenar)))
            .addGap(73, 73, 73))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(33, 33, 33)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabelNombre)
               .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(20, 20, 20)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabelMonto)
               .addComponent(jFormattedTextFieldMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jFormattedTextFieldFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabelFechaIngreso))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jFormattedTextFieldFechaRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabelFechaRetiro))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jFormattedTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabelCantidad))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jButtonEmpenar)
               .addComponent(jButtonLimpia))
            .addGap(18, 18, 18)
            .addComponent(jButtonAtras)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
      Principal princi = new Principal(datos);
      princi.setVisible(true);
      dispose();
   }//GEN-LAST:event_jButtonAtrasActionPerformed

   private void jButtonEmpenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpenarActionPerformed
      if (jTextFieldNombre.getText().isEmpty()) {
         JOptionPane.showMessageDialog(null, "El campo de nombre está vacio");
      }
      else if (jFormattedTextFieldMonto.getText().isEmpty()) {
         JOptionPane.showMessageDialog(null, "El campo de monto está vacio");
      }
      else if (jFormattedTextFieldFechaIngreso.getText().replaceAll("[ ,/]", "").length() != 8) {
         JOptionPane.showMessageDialog(null, "El campo de fecha está incompleto");
      }
      else if (jFormattedTextFieldFechaRetiro.getText().replaceAll("[ ,/]", "").length() != 8) {
         JOptionPane.showMessageDialog(null, "El campo de fecha está incompleto");
      }
      else if (jFormattedTextFieldCantidad.getText().isEmpty()) {
         JOptionPane.showMessageDialog(null, "El campo de cantidad está vacio");
      }
      else{
         if (datos.verificaEmpenio(jTextFieldNombre.getText(), Integer.parseInt(jFormattedTextFieldMonto.getText()), jFormattedTextFieldFechaIngreso.getText()
                 , jFormattedTextFieldFechaRetiro.getText(), Integer.parseInt(jFormattedTextFieldCantidad.getText()))) {
            limpiarFormulario();
         }
      }
   }//GEN-LAST:event_jButtonEmpenarActionPerformed

   private void jButtonLimpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiaActionPerformed
      limpiarFormulario();
   }//GEN-LAST:event_jButtonLimpiaActionPerformed

   private void limpiarFormulario(){
      jTextFieldNombre.setText("");
      jFormattedTextFieldMonto.setText("");
      jFormattedTextFieldFechaIngreso.setValue(null);
      jFormattedTextFieldFechaRetiro.setValue(null);
      jFormattedTextFieldCantidad.setText("");
   }
   
   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(Empenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(Empenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(Empenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Empenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new Empenio(datos).setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButtonAtras;
   private javax.swing.JButton jButtonEmpenar;
   private javax.swing.JButton jButtonLimpia;
   private javax.swing.JFormattedTextField jFormattedTextFieldCantidad;
   private javax.swing.JFormattedTextField jFormattedTextFieldFechaIngreso;
   private javax.swing.JFormattedTextField jFormattedTextFieldFechaRetiro;
   private javax.swing.JFormattedTextField jFormattedTextFieldMonto;
   private javax.swing.JLabel jLabelCantidad;
   private javax.swing.JLabel jLabelFechaIngreso;
   private javax.swing.JLabel jLabelFechaRetiro;
   private javax.swing.JLabel jLabelMonto;
   private javax.swing.JLabel jLabelNombre;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JTextField jTextFieldNombre;
   // End of variables declaration//GEN-END:variables
}
